import { join } from 'node:path';
import { mkdirSync } from 'node:fs';
import { PairingStore } from './pairing-store.js';
const directory = process.env.DATA_DIR ?? '.local';
mkdirSync(directory, { recursive: true });
const store = new PairingStore(join(directory, 'pairing.sqlite'));
export const createPairing = store.createPairing.bind(store);
export const pending = store.pending.bind(store);
export const claim = store.claim.bind(store);
export const devices = store.devices.bind(store);
export const disconnect = store.disconnect.bind(store);
export const status = store.status.bind(store);
